# Generated by Django 4.2 on 2023-04-18 07:09

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('displacement', models.IntegerField(default=3000)),
                ('cylinders', models.IntegerField(default=6)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.enginemaker')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('constructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='f1web.constructor')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='f1web.engine')),
            ],
        ),
    ]
