# Generated by Django 4.2 on 2023-04-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0002_alter_car_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='displacement',
        ),
    ]
