# Generated by Django 4.2 on 2023-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0003_remove_engine_cylinders_remove_engine_displacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(default=1980, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
