# Generated by Django 4.2 on 2023-04-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0004_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='cars',
            field=models.ManyToManyField(to='f1web.car'),
        ),
    ]
