# Generated by Django 4.2 on 2023-04-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0005_season_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='cars',
            field=models.ManyToManyField(blank=True, to='f1web.car'),
        ),
    ]
