# Generated by Django 4.2 on 2023-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0006_alter_season_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='f1web.constructor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.season')),
            ],
            options={
                'ordering': ('year', 'team'),
                'unique_together': {('team', 'year')},
            },
        ),
    ]
