# Generated by Django 4.2 on 2023-04-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0007_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='drives',
            field=models.ManyToManyField(to='f1web.drive'),
        ),
    ]
