# Generated by Django 4.2 on 2023-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0008_driver_drives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='drives',
            field=models.ManyToManyField(blank=True, to='f1web.drive'),
        ),
    ]
