# Generated by Django 4.2 on 2023-04-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0009_alter_driver_drives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('constructor', 'name')},
        ),
    ]
