# Generated by Django 4.2 on 2023-04-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0011_alter_drive_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructor',
            options={'ordering': ('name',)},
        ),
    ]
