# Generated by Django 4.2 on 2023-04-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0012_alter_constructor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('name',)},
        ),
    ]
