# Generated by Django 4.2 on 2023-04-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0014_alter_car_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.constructor')),
            ],
        ),
    ]
