# Generated by Django 4.2 on 2023-04-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0020_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f1web.constructor'),
        ),
        migrations.AlterUniqueTogether(
            name='drivingcontract',
            unique_together={('season', 'team', 'driver')},
        ),
    ]
