# Generated by Django 4.2 on 2023-05-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0021_alter_car_constructor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('constructor', 'name')},
        ),
    ]
