# Generated by Django 4.2 on 2023-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0024_alter_enginemaker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingcontract',
            name='car_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='constructors_champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='f1web.constructor'),
        ),
        migrations.AddField(
            model_name='season',
            name='drivers_champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='f1web.driver'),
        ),
    ]
