# Generated by Django 4.2 on 2023-05-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0025_drivingcontract_car_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingcontract',
            name='car_number',
        ),
        migrations.AddField(
            model_name='drivingcontract',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CarNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1web.constructor')),
            ],
        ),
    ]
