# Generated by Django 4.2 on 2023-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0027_alter_carnumber_options_constructor_is_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='carnumber',
            unique_together={('season', 'team')},
        ),
    ]
