# Generated by Django 4.2 on 2023-05-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0028_alter_carnumber_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivingcontract',
            options={'ordering': ('season', 'team', 'is_lead', 'driver')},
        ),
    ]
