# Generated by Django 4.2 on 2023-05-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0029_alter_drivingcontract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivingcontract',
            options={'ordering': ('season', 'team', '-is_lead', 'driver')},
        ),
    ]
