# Generated by Django 3.2 on 2023-11-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0030_alter_drivingcontract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterField(
            model_name='carnumber',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enginemaker',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveSmallIntegerField(default=1980, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1web.season')),
            ],
        ),
    ]
