# Generated by Django 3.2 on 2023-11-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0031_auto_20231120_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('season',)},
        ),
        migrations.AlterUniqueTogether(
            name='carnumber',
            unique_together={('season', 'team', 'number')},
        ),
    ]
