# Generated by Django 3.2 on 2023-11-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0032_auto_20231122_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carnumber',
            unique_together={('season', 'number')},
        ),
    ]
