# Generated by Django 3.2 on 2023-12-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0034_alter_carnumber_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carnumber',
            unique_together={('season', 'number')},
        ),
    ]
