# Generated by Django 3.2 on 2024-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0036_alter_carnumber_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='span',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
