# Generated by Django 3.2 on 2024-05-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0037_carnumber_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1web.constructor')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_names', to='f1web.constructor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f1web.season')),
            ],
            options={
                'ordering': ('season',),
            },
        ),
    ]
