# Generated by Django 3.2 on 2024-10-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0038_constructortransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingcontract',
            name='starting_round',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='constructortransfer',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previously', to='f1web.constructor'),
        ),
        migrations.AlterField(
            model_name='constructortransfer',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsequently', to='f1web.constructor'),
        ),
    ]
