# Generated by Django 3.2 on 2025-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0039_auto_20241024_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
