# Generated by Django 3.2 on 2025-01-23 13:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0039_auto_20241024_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=64, null=True)),
                ('set_description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentSetCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='f1web.permanentset')),
            ],
        ),
    ]
