# Generated by Django 3.2 on 2025-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0040_permanentset_permanentsetcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentset',
            name='set_name',
            field=models.CharField(default=3, max_length=64),
            preserve_default=False,
        ),
    ]
