# Generated by Django 3.2 on 2025-04-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0041_alter_permanentset_set_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivingcontract',
            unique_together={('season', 'team', 'driver', 'is_lead')},
        ),
    ]
