# Generated by Django 3.2 on 2025-04-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1web', '0040_season_rounds'),
        ('f1web', '0042_alter_drivingcontract_unique_together'),
    ]

    operations = [
    ]
